'use server';
/**
 * @fileOverview An AI agent that assesses the health risk level based on medical report text.
 *
 * - assessHealthRisk - A function that handles the health risk assessment process.
 * - AssessHealthRiskInput - The input type for the assessHealthRisk function.
 * - AssessHealthRiskOutput - The return type for the assessHealthRisk function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AssessHealthRiskInputSchema = z.object({
  reportText: z.string().describe('The extracted text content of the medical report.'),
});
export type AssessHealthRiskInput = z.infer<typeof AssessHealthRiskInputSchema>;

const AssessHealthRiskOutputSchema = z.object({
  riskLevel: z
    .enum(['Low Risk', 'Moderate Risk', 'High Risk', 'Critical'])
    .describe('The assessed health risk level.'),
  riskReason:
    z.string().describe('A concise explanation for the assessed health risk level.'),
  disclaimer:
    z.string().describe('A disclaimer stating that the explanation is for educational purposes and not for diagnosis.'),
});
export type AssessHealthRiskOutput = z.infer<typeof AssessHealthRiskOutputSchema>;

export async function assessHealthRisk(input: AssessHealthRiskInput): Promise<AssessHealthRiskOutput> {
  return assessHealthRiskFlow(input);
}

const prompt = ai.definePrompt({
  name: 'assessHealthRiskPrompt',
  input: {schema: AssessHealthRiskInputSchema},
  output: {schema: AssessHealthRiskOutputSchema},
  prompt: `You are an AI assistant specialized in analyzing medical reports to assess potential health risk levels.
Your task is to review the provided medical report text and determine a health risk level from 'Low Risk', 'Moderate Risk', 'High Risk', or 'Critical'. Provide a concise explanation for this risk level.

IMPORTANT: This is NOT for diagnosis. Your role is only to explain potential risks based on the report findings, not to diagnose any condition.

Medical Report Text:
{{{reportText}}}

Always include the following disclaimer in your output:
"This explanation is generated by AI and is intended for educational purposes only. Please consult a qualified healthcare professional for diagnosis and treatment."

Based on the report text, determine the risk level, provide a reason, and include the disclaimer. Return the output in JSON format as specified by the output schema.`,
});

const assessHealthRiskFlow = ai.defineFlow(
  {
    name: 'assessHealthRiskFlow',
    inputSchema: AssessHealthRiskInputSchema,
    outputSchema: AssessHealthRiskOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    if (!output) {
      throw new Error('Failed to get a valid output from the AI model.');
    }
    return output;
  }
);
