'use server';
/**
 * @fileOverview A Genkit flow that explains prescribed medicines from a doctor's prescription.
 *
 * - explainPrescription - A function that handles the medicine explanation process.
 * - ExplainPrescriptionInput - The input type for the explainPrescription function.
 * - ExplainPrescriptionOutput - The return type for the explainPrescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainPrescriptionInputSchema = z.object({
  prescriptionText: z.string().describe('The doctor\'s prescription text containing medicine names and instructions.'),
});
export type ExplainPrescriptionInput = z.infer<typeof ExplainPrescriptionInputSchema>;

const MedicineExplanationSchema = z.object({
  medicineName: z.string().describe('The name of the medicine.'),
  purpose: z.string().describe('The purpose of the medicine.'),
  commonUsage: z.string().describe('Common usage and dosage instructions for the medicine.'),
  commonSideEffects: z.string().describe('Common side effects of the medicine.'),
  generalPrecautions: z.string().describe('General precautions to take when using this medicine.'),
  foodInteraction: z.string().optional().describe('Whether to take before/after food if commonly known, or any known food interactions.'),
});

const ExplainPrescriptionOutputSchema = z.object({
  medicineExplanations: z.array(MedicineExplanationSchema).describe('An array of explanations for each medicine found in the prescription.'),
  disclaimer: z.string().describe('A disclaimer stating that this explanation is generated by AI and is for educational purposes only, not medical advice.'),
});
export type ExplainPrescriptionOutput = z.infer<typeof ExplainPrescriptionOutputSchema>;

export async function explainPrescription(input: ExplainPrescriptionInput): Promise<ExplainPrescriptionOutput> {
  return explainPrescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainPrescriptionPrompt',
  input: {schema: ExplainPrescriptionInputSchema},
  output: {schema: ExplainPrescriptionOutputSchema},
  prompt: `You are an AI assistant specialized in simplifying medical information. Your task is to analyze the provided doctor\'s prescription text, identify each medicine, and for each medicine, explain its purpose, common usage, common side effects, general precautions, and any commonly known food interactions.\n\nIt is crucial that you NEVER generate dangerous medical advice. Your output must strictly adhere to the provided JSON schema.\n\nAlways include the following disclaimer in the output: "This explanation is generated by AI and is intended for educational purposes only. Please consult a qualified healthcare professional for diagnosis and treatment."\n\nPrescription Text:\n{{{prescriptionText}}}`,
});

const explainPrescriptionFlow = ai.defineFlow(
  {
    name: 'explainPrescriptionFlow',
    inputSchema: ExplainPrescriptionInputSchema,
    outputSchema: ExplainPrescriptionOutputSchema,
  },
  async (input) => {
    const {output} = await prompt(input);
    return output!;
  }
);
