'use server';
/**
 * @fileOverview This flow generates intelligent questions for a user to ask their doctor based on a simplified medical report.
 *
 * - generateDoctorQuestions - A function that generates a list of questions for the doctor.
 * - GenerateDoctorQuestionsInput - The input type for the generateDoctorQuestions function.
 * - GenerateDoctorQuestionsOutput - The return type for the generateDoctorQuestions function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDoctorQuestionsInputSchema = z.object({
  simplifiedReportSummary: z
    .string()
    .describe('A simplified summary of the medical report.'),
  importantFindings: z
    .array(z.string())
    .describe('A list of important findings from the medical report.'),
  abnormalValues: z
    .array(z.string())
    .describe('A list of abnormal values detected in the medical report.'),
  possibleConcerns: z
    .string()
    .describe(
      'A description of possible concerns or risk reasons identified in the report.'
    ),
});
export type GenerateDoctorQuestionsInput = z.infer<
  typeof GenerateDoctorQuestionsInputSchema
>;

const GenerateDoctorQuestionsOutputSchema = z
  .array(z.string())
  .describe('A list of intelligent questions for the doctor.');
export type GenerateDoctorQuestionsOutput = z.infer<
  typeof GenerateDoctorQuestionsOutputSchema
>;

export async function generateDoctorQuestions(
  input: GenerateDoctorQuestionsInput
): Promise<GenerateDoctorQuestionsOutput> {
  return generateDoctorQuestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateDoctorQuestionsPrompt',
  input: {schema: GenerateDoctorQuestionsInputSchema},
  output: {schema: GenerateDoctorQuestionsOutputSchema},
  prompt: `You are an AI assistant designed to help patients formulate intelligent questions for their doctor after reviewing a simplified medical report. Your goal is to empower the user to have a more productive conversation with their healthcare professional.

Based on the provided simplified medical report summary, important findings, abnormal values, and possible concerns, generate a list of 5-10 specific and relevant questions for the user to ask their doctor. These questions should help clarify the report, understand next steps, and address any potential health implications. Do NOT provide any diagnostic information or medical advice.

Examples of the type of questions to generate include:
- "Should I repeat this test?"
- "Is medication necessary for these findings?"
- "What could be the underlying cause of this abnormal value?"
- "Should I consult a specialist regarding these results?"
- "Are there any additional tests or screenings I should consider?"

Always include the disclaimer: "This explanation is generated by AI and is intended for educational purposes only. Please consult a qualified healthcare professional for diagnosis and treatment."

Simplified Report Summary: {{{simplifiedReportSummary}}}
Important Findings: {{#each importantFindings}}- {{{this}}}\n{{/each}}
Abnormal Values: {{#each abnormalValues}}- {{{this}}}\n{{/each}}
Possible Concerns: {{{possibleConcerns}}}

Generate the questions as a JSON array of strings.`,
});

const generateDoctorQuestionsFlow = ai.defineFlow(
  {
    name: 'generateDoctorQuestionsFlow',
    inputSchema: GenerateDoctorQuestionsInputSchema,
    outputSchema: GenerateDoctorQuestionsOutputSchema,
  },
  async (input) => {
    const {output} = await prompt(input);
    return output!;
  }
);
