'use server';
/**
 * @fileOverview A Genkit flow for simplifying medical reports.
 *
 * - simplifyMedicalReport - A function that processes an uploaded medical report (text content)
 *   and returns a simplified, human-understandable explanation in a structured JSON format.
 * - SimplifyMedicalReportInput - The input type for the simplifyMedicalReport function.
 * - SimplifyMedicalReportOutput - The return type for the simplifyMedicalReport function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const SimplifyMedicalReportInputSchema = z.object({
  reportText: z.string().describe('The extracted text content of the medical report.'),
});
export type SimplifyMedicalReportInput = z.infer<typeof SimplifyMedicalReportInputSchema>;

const MedicalTermSchema = z.object({
  term: z.string().describe('The difficult medical term.'),
  definition: z.string().describe('A simple definition of the term.'),
  meaning: z.string().describe('The significance or context of the term in the report.'),
  whyImportant: z.string().describe('Why this term is important for the user to know.'),
  normalRange: z.string().optional().describe('The normal range or value for this term, if applicable.'),
});

const MedicineExplanationSchema = z.object({
  medicineName: z.string().describe('The name of the medicine.'),
  purpose: z.string().describe('The main purpose of the medicine.'),
  commonUsage: z.string().describe('How the medicine is commonly used.'),
  sideEffects: z.string().describe('Common side effects of the medicine.'),
  precautions: z.string().describe('General precautions to take with this medicine.'),
  takeBeforeAfterFood: z.string().optional().describe('Instructions regarding taking the medicine before or after food, if commonly known.'),
});

const SimplifyMedicalReportOutputSchema = z.object({
  summary: z.string().describe('A concise summary of the entire medical report.'),
  simpleEnglish: z.string().describe('A detailed explanation of the report in simple English.'),
  simpleHindi: z.string().describe('A detailed explanation of the report in simple Hindi.'),
  riskLevel: z.enum(['Low Risk', 'Moderate Risk', 'High Risk', 'Critical']).describe('The overall risk level based on the report findings.'),
  riskReason: z.string().describe('The primary reasons for the assigned risk level.'),
  importantFindings: z.array(z.string()).describe('A list of the most important findings from the report.'),
  normalValues: z.array(z.string()).describe('A list of values that are within the normal range.'),
  abnormalValues: z.array(z.string()).describe('A list of values that are outside the normal range, indicating potential issues.'),
  medicalTerms: z.array(MedicalTermSchema).describe('A list of difficult medical terms found in the report with their definitions and importance.'),
  medicineExplanation: z.array(MedicineExplanationSchema).describe('A list of medicines mentioned in prescriptions with their purpose, usage, side effects, and precautions.'),
  doctorQuestions: z.array(z.string()).describe('A list of intelligent questions a user might ask their doctor based on the report.'),
  lifestyleSuggestions: z.array(z.string()).describe('General lifestyle suggestions based on the report for diet, exercise, sleep, etc.'),
  emergencyWarning: z.boolean().describe('True if the report contains dangerous indicators requiring urgent medical attention.'),
  disclaimer: z.string().describe('A mandatory disclaimer stating that this is not for diagnosis.'),
});
export type SimplifyMedicalReportOutput = z.infer<typeof SimplifyMedicalReportOutputSchema>;

export async function simplifyMedicalReport(input: SimplifyMedicalReportInput): Promise<SimplifyMedicalReportOutput> {
  return simplifyMedicalReportFlow(input);
}

const prompt = ai.definePrompt({
  name: 'simplifyMedicalReportPrompt',
  input: { schema: SimplifyMedicalReportInputSchema },
  output: { schema: SimplifyMedicalReportOutputSchema },
  prompt: `You are an AI-powered medical report simplifier. Your task is to analyze the provided medical report text and convert its complex medical language into easily understandable terms for ordinary people. It is critical that you NEVER attempt to diagnose diseases or provide medical advice.

ALWAYS include the following disclaimer at the end of your response:
"This explanation is generated by AI and is intended for educational purposes only. Please consult a qualified healthcare professional for diagnosis and treatment."

Medical Report Text:
{{{reportText}}}

Instructions:
1. Provide a concise overall summary.
2. Explain the entire report in simple English, avoiding jargon.
3. Provide a Hindi translation of the simple explanation.
4. Assess the risk level (Low, Moderate, High, Critical) and give a reason.
5. List normal and abnormal findings separately.
6. Extract and define any difficult medical terms used in the report.
7. If any medications are mentioned, provide their details (purpose, side effects, etc.).
8. Suggest 5-10 questions the user should ask their doctor.
9. Provide lifestyle suggestions based on the findings.
10. Flag if there are any life-threatening emergency indicators.`,
});

const simplifyMedicalReportFlow = ai.defineFlow(
  {
    name: 'simplifyMedicalReportFlow',
    inputSchema: SimplifyMedicalReportInputSchema,
    outputSchema: SimplifyMedicalReportOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    if (!output) {
      throw new Error('Failed to generate simplified report.');
    }
    return output;
  }
);
